// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsycwdpzcnlwllynurgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzeWN3ZHB6Y25sd2xseW51cmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTIwNTYsImV4cCI6MjA2Njg2ODA1Nn0.IsO9uBZd5wXe-pjTqzIVKyXp5lL7d_FXuugt3j9hGDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});